<?php

use App\Http\Controllers\SchoolController;
use Illuminate\Support\Facades\Route;

Route::prefix('school')->middleware(['auth:sanctum', 'active', 'locale', \App\Http\Middleware\InstitutionalWriteTransaction::class])->group(function () {
    Route::get('/', [SchoolController::class, 'index']);
    Route::get('/deadlines', [SchoolController::class, 'deadlines']);
    Route::post('/years', [SchoolController::class, 'createYear']);
    Route::patch('/years/{year}', [SchoolController::class, 'updateYear']);
    Route::post('/years/{year}/archive', [SchoolController::class, 'archiveYear']);
    Route::get('/assignment-requests', [SchoolController::class, 'assignmentRequests']);
    Route::post('/setup-requests', [SchoolController::class, 'setupRequest'])->middleware('throttle:10,60');
    Route::post('/assignment-requests/{assignment}/resolve', [SchoolController::class, 'resolveRequest']);
    Route::post('/groups', [SchoolController::class, 'createGroup']);
    Route::patch('/groups/{group}', [SchoolController::class, 'updateGroup']);
    Route::post('/groups/{group}/invitation', [SchoolController::class, 'invitation']);
    Route::post('/modules', [SchoolController::class, 'createModule']);
    Route::patch('/modules/{module}', [SchoolController::class, 'updateModule']);
    Route::post('/groups/{group}/offerings', [SchoolController::class, 'createOffering']);
    Route::patch('/offerings/{offering}', [SchoolController::class, 'updateOffering']);
    Route::post('/offerings/{offering}/teachers', [SchoolController::class, 'assign']);
    Route::delete('/teaching-assignments/{assignment}', [SchoolController::class, 'revokeAssignment']);
    Route::put('/groups/{group}/coordinator', [SchoolController::class, 'coordinator']);
    Route::get('/groups/{group}/roster', [SchoolController::class, 'roster']);
    Route::get('/groups/{group}/requests', [SchoolController::class, 'pending']);
    Route::post('/memberships/{membership}/decision', [SchoolController::class, 'decide']);
    Route::post('/offerings/{offering}/assignment-request', [SchoolController::class, 'requestAssignment']);
    Route::post('/groups/{group}/enrollments', [SchoolController::class, 'enroll']);
    Route::delete('/groups/{group}/enrollments/{student}', [SchoolController::class, 'remove']);
    Route::post('/groups/{group}/enrollments/{student}/transfer', [SchoolController::class, 'transfer']);
    Route::post('/groups/{group}/delegates', [SchoolController::class, 'appoint']);
    Route::delete('/delegates/{delegate}', [SchoolController::class, 'revokeDelegate']);
    Route::post('/groups/{group}/activate', [SchoolController::class, 'activate']);
    Route::post('/groups/{group}/archive', [SchoolController::class, 'archive']);
    Route::post('/groups/{group}/restore', [SchoolController::class, 'restore']);
    Route::get('/people', [SchoolController::class, 'people']);
    Route::get('/groups/{group}/contacts', [SchoolController::class, 'contacts']);
    Route::get('/groups/{group}/partners', [SchoolController::class, 'partners'])->middleware('role:student');
    Route::post('/groups/{group}/partner-requests', [SchoolController::class, 'requestPartner'])->middleware(['role:student', 'throttle:30,1']);
    Route::post('/partner-requests/{partner}/respond', [SchoolController::class, 'respondPartner'])->middleware(['role:student', 'throttle:30,1']);
    Route::post('/groups/{group}/roster-imports/preview', [SchoolController::class, 'previewRoster']);
    Route::post('/groups/{group}/roster-imports/commit', [SchoolController::class, 'commitRoster']);
    Route::post('/offerings/{offering}/access-grants', [SchoolController::class, 'grantModule']);
    Route::get('/offerings/{offering}/access-grants', [SchoolController::class, 'moduleGrants']);
    Route::delete('/offerings/{offering}/access-grants/{student}', [SchoolController::class, 'revokeModule']);
    Route::get('/offerings/{offering}/assessments', [\App\Http\Controllers\OfficialGradeController::class, 'index']);
    Route::post('/offerings/{offering}/assessments', [\App\Http\Controllers\OfficialGradeController::class, 'create']);
    Route::get('/assessments/{assessment}', [\App\Http\Controllers\OfficialGradeController::class, 'show']);
    Route::put('/assessments/{assessment}/draft', [\App\Http\Controllers\OfficialGradeController::class, 'save']);
    Route::get('/assessments/{assessment}/template', [\App\Http\Controllers\OfficialGradeController::class, 'template']);
    Route::post('/assessments/{assessment}/imports/preview', [\App\Http\Controllers\OfficialGradeController::class, 'preview']);
    Route::post('/assessments/{assessment}/imports/commit', [\App\Http\Controllers\OfficialGradeController::class, 'commit']);
    Route::post('/assessments/{assessment}/publish', [\App\Http\Controllers\OfficialGradeController::class, 'publish']);
    Route::post('/assessments/{assessment}/correction', [\App\Http\Controllers\OfficialGradeController::class, 'correction']);
    Route::get('/my-grades', [\App\Http\Controllers\OfficialGradeController::class, 'results']);
    Route::get('/my-grades/export', [\App\Http\Controllers\OfficialGradeController::class, 'exportOwn']);
    Route::get('/my-grades/{assessment}/contacts', [\App\Http\Controllers\OfficialGradeController::class, 'ownContacts']);
    Route::get('/my-grades/{assessment}', [\App\Http\Controllers\OfficialGradeController::class, 'ownResult']);
    Route::post('/assessments/{assessment}/roster-reconcile', [\App\Http\Controllers\OfficialGradeController::class, 'reconcile']);
    Route::get('/threads', [\App\Http\Controllers\SchoolCommunicationController::class, 'index']);
    Route::get('/support-contacts', [\App\Http\Controllers\SchoolCommunicationController::class, 'supportContacts']);
    Route::get('/reports', [\App\Http\Controllers\SchoolCommunicationController::class, 'reports']);
    Route::patch('/reports/{report}', [\App\Http\Controllers\SchoolCommunicationController::class, 'respondReport']);
    Route::post('/threads/{thread}/report', [\App\Http\Controllers\SchoolCommunicationController::class, 'report'])->middleware('throttle:10,60');
    Route::post('/threads', [\App\Http\Controllers\SchoolCommunicationController::class, 'create'])->middleware('throttle:30,1');
    Route::get('/threads/{thread}', [\App\Http\Controllers\SchoolCommunicationController::class, 'show']);
    Route::post('/threads/{thread}/messages', [\App\Http\Controllers\SchoolCommunicationController::class, 'send'])->middleware('throttle:30,1');
    Route::post('/threads/{thread}/resolve', [\App\Http\Controllers\SchoolCommunicationController::class, 'resolve']);
    Route::post('/notices/preview', [\App\Http\Controllers\SchoolCommunicationController::class, 'previewNotice'])->middleware('throttle:30,1');
    Route::post('/notices/publish', [\App\Http\Controllers\SchoolCommunicationController::class, 'publishNotice'])->middleware('throttle:30,1');
    Route::match(['get', 'post'], '/offerings/{offering}/tools/{kind}', [\App\Http\Controllers\SchoolTeachingController::class, 'collection']);
    Route::match(['get', 'post', 'patch', 'delete'], '/offerings/{offering}/tools/{kind}/{record}/{action?}', [\App\Http\Controllers\SchoolTeachingController::class, 'record']);
});
